### ISSUE TITLE
 Username Invalid username or password in installation Step 4

### ISSUE THREAD

**Issue by elmokhtar-mohamedmoussa-idnow** [mammoth-eu/mammoth-toolkit-releases#1]
Hello, 
I have an issue in Step 4: after creating a user from the admin page, I am not able to authenticate my self in the mammoth toolkit page.

![Screenshot from 2024-06-10 08-50-23](https://github.com/mammoth-eu/mammoth-toolkit-releases/assets/160246047/4e34e4db-c5ed-44a0-8e4d-032630824d03)
Figure 1: creating a user "test"
![Screenshot from 2024-06-10 08-56-20](https://github.com/mammoth-eu/mammoth-toolkit-releases/assets/160246047/639ec76d-7b1e-4902-abaf-c62db0b47a21)
Figure 2: adding a password
![Screenshot from 2024-06-10 08-51-48](https://github.com/mammoth-eu/mammoth-toolkit-releases/assets/160246047/1ab15064-d22a-4716-b60d-8fab1d0e8542)
Figure 3: credentials rejected.

**Comment by georgiosn** [comment]
Did you selected the **toolkit** option from the drop down at the left or you created the user at master?

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
I forgot, thank you. I can log to the toolkit now.
