### ISSUE TITLE
In-platform module importer

### ISSUE THREAD

**Issue by maniospas** [mammoth-eu/mammoth-toolkit-releases#4]
**Summary:** Give the option to the user to import new or updated modules. The import should occur from within the UI.

**Necessary for beta (internally tested first variation by end-of-October):** Yes

**Details**: The modules can be found from the web, especially GitHub, in which case their metadata files should be automatically downloaded. and placed in the correct folder To begin with, the importer could have two fields - one for each needed type of metadata. The process should be fully automated, to let the users feel like they are working in an environment. 

Once the mechanism is in place, we can consider a producing a yaml with mammoth-commons that encloses both types of configurations, and which upon download it split into two files (I can provide code for this).

Consider also a drag&drop approach of URL links (like Eclipse does when installing extensions.)

P.S. Please create some basic labels (feature, improvement, bug, etc)

**Comment by georgiosn** [comment]
Available on latest release.
