### ISSUE TITLE
Create success or failure message for the creation of new runs

### ISSUE THREAD

**Issue by maniospas** [mammoth-eu/mammoth-toolkit-releases#7]
**Summary:** Please make sure that the user is aware of whether they successfully submitted a run, or if there was some failure in starting the run process (this is different than getting run progress).

**Necessary for beta (internally tested first variation by end-of-October):** Yes

**Details:** Currently, there is no way to tell from within the application if anything is working at all. This is pretty important for the first runs with a new version of the toolkit, where I personally have no idea if there is an issue with the installation, with some module, or with the input data. Realistically, we can expect most users that reach a similar state to just abandon the toolkit.

**Comment by georgiosn** [comment]
Available in last release.
